a = struct( ...
    'shipping_address', ...
        struct('street_address', '1600 Penn Ave NW', 'city', 'Washington', 'state', 'DC'), ...
    'billing_address', ...
        struct('street_address', '1st Street SE', 'city', 'Washington', 'state', 'DC'));